spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.90.212:3306/medical_advice
    username: root
    password: root
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
